version: '3.4'

services:
  fooddeliveryapi:
    image: fooddeliveryapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development